/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./src/components/Home/About.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Presence: typeof import('./src/components/Home/Presence.vue')['default']
    Profile: typeof import('./src/components/Home/Profile.vue')['default']
    Projects: typeof import('./src/components/Home/Projects.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopMusic: typeof import('./src/components/Home/TopMusic.vue')['default']
  }
}
