/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        404: typeof import('./views/404.vue')['default']
        About: typeof import('./views/About.vue')['default']
        ArrowDown: typeof import('./assets/svg/ArrowDown.vue')['default']
        ArrowLeft: typeof import('./assets/svg/ArrowLeft.vue')['default']
        ArrowUpRight: typeof import('./assets/svg/ArrowUpRight.vue')['default']
        AtSign: typeof import('./assets/svg/AtSign.vue')['default']
        BackButton: typeof import('./components/shared/BackButton.vue')['default']
        Branch: typeof import('./assets/svg/Branch.vue')['default']
        Card: typeof import('./components/About/Card.vue')['default']
        Discord: typeof import('./assets/svg/Discord.vue')['default']
        Donate: typeof import('./components/About/Donate.vue')['default']
        GitHub: typeof import('./assets/svg/GitHub.vue')['default']
        Goals: typeof import('./components/About/Goals.vue')['default']
        Heart: typeof import('./assets/svg/Heart.vue')['default']
        Home: typeof import('./views/Home.vue')['default']
        Info: typeof import('./components/About/Info.vue')['default']
        Link: typeof import('./components/shared/Link.vue')['default']
        LinkedIn: typeof import('./assets/svg/LinkedIn.vue')['default']
        Moon: typeof import('./assets/svg/Moon.vue')['default']
        Music: typeof import('./assets/svg/Music.vue')['default']
        Navbar: typeof import('./components/Home/Navbar.vue')['default']
        Profile: typeof import('./components/Home/Profile.vue')['default']
        ProfileSkeleton: typeof import('./components/Home/ProfileSkeleton.vue')['default']
        ProjectList: typeof import('./components/Projects/ProjectList.vue')['default']
        ProjectListSkeleton: typeof import('./components/Projects/ProjectListSkeleton.vue')['default']
        Projects: typeof import('./views/Projects.vue')['default']
        Repo: typeof import('./components/Projects/Repo.vue')['default']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
        SongCard: typeof import('./components/Songs/SongCard.vue')['default']
        SongList: typeof import('./components/Songs/SongList.vue')['default']
        Songs: typeof import('./views/Songs.vue')['default']
        Spotify: typeof import('./components/Songs/Spotify.vue')['default']
        SpotifySkeleton: typeof import('./components/Songs/SpotifySkeleton.vue')['default']
        Star: typeof import('./assets/svg/Star.vue')['default']
        Sun: typeof import('./assets/svg/Sun.vue')['default']
    }
}
