/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./views/About.vue')['default']
    Home: typeof import('./views/Home.vue')['default']
    Navbar: typeof import('./components/Home/Navbar.vue')['default']
    Profile: typeof import('./components/Home/Profile.vue')['default']
    ProfileSkeleton: typeof import('./components/Home/ProfileSkeleton.vue')['default']
    Project: typeof import('./components/Projects/Project.vue')['default']
    ProjectList: typeof import('./components/Projects/ProjectList.vue')['default']
    Projects: typeof import('./views/Projects.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Song: typeof import('./components/Songs/Song.vue')['default']
    SongList: typeof import('./components/Songs/SongList.vue')['default']
    Songs: typeof import('./views/Songs.vue')['default']
    Spotify: typeof import('./components/Songs/Spotify.vue')['default']
  }
}
