/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    404: typeof import('./views/404.vue')['default']
    About: typeof import('./views/About.vue')['default']
    ArrowLeft: typeof import('./assets/svg/ArrowLeft.vue')['default']
    AtSign: typeof import('./assets/svg/AtSign.vue')['default']
    BackButton: typeof import('./components/BackButton.vue')['default']
    Discord: typeof import('./assets/svg/Discord.vue')['default']
    Donation: typeof import('./components/About/Donation.vue')['default']
    GitHub: typeof import('./assets/svg/GitHub.vue')['default']
    Home: typeof import('./views/Home.vue')['default']
    LinkedIn: typeof import('./assets/svg/LinkedIn.vue')['default']
    Moon: typeof import('./assets/svg/Moon.vue')['default']
    Music: typeof import('./assets/svg/Music.vue')['default']
    Navbar: typeof import('./components/Home/Navbar.vue')['default']
    Profile: typeof import('./components/Home/Profile.vue')['default']
    ProfileSkeleton: typeof import('./components/Home/ProfileSkeleton.vue')['default']
    Project: typeof import('./components/Projects/Project.vue')['default']
    ProjectList: typeof import('./components/Projects/ProjectList.vue')['default']
    Projects: typeof import('./views/Projects.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Song: typeof import('./components/Songs/Song.vue')['default']
    SongList: typeof import('./components/Songs/SongList.vue')['default']
    Songs: typeof import('./views/Songs.vue')['default']
    Spotify: typeof import('./components/Songs/Spotify.vue')['default']
    SpotifySkeleton: typeof import('./components/Songs/SpotifySkeleton.vue')['default']
    Sun: typeof import('./assets/svg/Sun.vue')['default']
  }
}
